wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1703166993.386251
    t:
      1:
      - 55
      - 95
      - 105
      2:
      - 55
      - 95
      - 105
      3:
      - 2
      - 23
      4: 3.10.9
      5: 0.16.1
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
